#pragma once
#ifndef FX_FLAGS_H
#define FX_FLAGS_H

#define SF_PARTICLESHOOTER_REPEATABLE 1
#define SF_PARTICLESHOOTER_SPIRAL 2
#define SF_PARTICLESHOOTER_COLLIDE_WITH_WORLD 4
#define SF_PARTICLESHOOTER_AFFECTED_BY_FORCE 8
#define SF_PARTICLESHOOTER_ANIMATED 16
#define SF_PARTICLESHOOTER_STARTON 32
#define SF_PARTICLESHOOTER_KILLED_ON_COLLIDE 64
#define SF_PARTICLESHOOTER_RIPPLE_WHEN_HITTING_WATER 128

#endif
