#pragma once
#if !defined(WEAPON_IDS_H)
#define WEAPON_IDS_H

#define WEAPON_NONE				0
#define WEAPON_CROWBAR			1
#define	WEAPON_GLOCK			2
#define WEAPON_PYTHON			3
#define WEAPON_MP5				4
#define WEAPON_MINIGUN			5
#define WEAPON_CROSSBOW			6
#define WEAPON_SHOTGUN			7
#define WEAPON_RPG				8
#define WEAPON_GAUSS			9
#define WEAPON_EGON				10
#define WEAPON_HORNETGUN		11
#define WEAPON_HANDGRENADE		12
#define WEAPON_TRIPMINE			13
#define	WEAPON_SATCHEL			14
#define	WEAPON_SNARK			15

#define WEAPON_GRAPPLE			16
#define WEAPON_EAGLE			17
#define WEAPON_PIPEWRENCH		18
#define	WEAPON_M249				19
#define WEAPON_DISPLACER		20
#define WEAPON_MEDKIT			21
#define WEAPON_SHOCKRIFLE		22
#define WEAPON_SPORELAUNCHER	23
#define WEAPON_SNIPERRIFLE		24
#define WEAPON_KNIFE			25
#define	WEAPON_PENGUIN			26
#define WEAPON_UZI				27

#define WEAPON_FLAMETHROWER		28
#define WEAPON_NAILGUN			29
#define WEAPON_GRENADE_LAUNCHER	30

#define WEAPON_M4A1				31

#define WEAPON_MELEE			48

#define WEAPON_PISTOL			50
#define WEAPON_PISTOL2			51
#define WEAPON_SMG				52
#define WEAPON_SMG2				53
#define WEAPON_RIFLE			54
#define WEAPON_RIFLE2			55
#define WEAPON_SHOTGUN2			56
#define WEAPON_SNIPERRIFLE2		57

#define WEAPON_THROWABLE		58

#define WEAPON_CAMERA			60
#define WEAPON_RADIO			61

#define WEAPON_TOOL				63

#endif
