#pragma once
#ifndef FEATURES_H
#define FEATURES_H

// New monsters
#define FEATURE_ZOMBIE_BARNEY
#define FEATURE_ZOMBIE_SOLDIER
#define FEATURE_GONOME
#define FEATURE_PITDRONE
#define FEATURE_SHOCKTROOPER
#define FEATURE_VOLTIFORE
#define FEATURE_MASSN
#define FEATURE_BLACK_APACHE
#define FEATURE_OTIS
#define FEATURE_CLEANSUIT_SCIENTIST

#ifdef FEATURE_MASSN
#define FEATURE_BLACK_OSPREY
#endif

#endif
